# Generated by Django 5.0.6 on 2024-05-18 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_joueur_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipe',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
